import dynamic from 'next/dynamic';
import type { Metadata } from "next";
import React from 'react';
import "./globals.css";


import Layout from 'antd/es/layout';

const AppSider = dynamic(() => import('@/components/primary-ui/AppSider'), { ssr: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Layout style={{ minHeight: '100vh' }}>
          <AppSider />
          <Layout>
            {children}
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
