import dynamic from 'next/dynamic';
import type { Metadata } from "next";
import React from 'react';
import "../globals.css";


import Layout from 'antd/es/layout';

const AppSider = dynamic(() => import('@/components/primary-ui/AppSider'), { ssr: true });

export const metadata: Metadata = {
  title: "Sidebar App",
  description: "Generated by create next app",
};

export default function TaskManagementLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout style={{ minHeight: '100vh' }}>
      <AppSider />
      <Layout>
        {children}
      </Layout>
    </Layout>
  );
}
